[[outputs]]
bearing_roller = {quantity=1}

# inputs list, similar to a cargo.toml file
[[inputs]]
bearing_hub_top = {version=0.1, type="printed"}
bearing_hub = {version=0.1, type="printed"}

# alternate representation of an element of the inputs list
[[inputs.m4_20_shcs]]
type = "M4x20 SHCS"
quantity = 3
comment = """These will hold the bearing rollers.  Possibly Button Heads
Cap Screws would be better?  Probably either will work fine."""

[[inputs.m4_washer]]
type = "M4 washer"
quantity = 6
dimensions = "12 mm OD, 4.4 mm ID, 1 mm thick"
comment = """The upstream repo calls for 12 mm OD but i think that's
too big, it hits the outer race of the bearings.  Use 8mm OD instead."""

[[inputs.624_bearing]]
type = "624 bearing"
quantity = 6
comments = "13mm OD, 4mm ID, 5mm wide"

[[inputs.m4_nuts]]
type = "M4 nuts"
quantity = 3

[[dependencies]]
tools = [
    "3 mm hex driver",
    "7 mm nut driver",
]
operator = {skill="assembly"}


[[action]]
process = """Assemble the bearing roller.  Each of the three roller
stacks will consist of: washer, bearing, bearing, washer.  All three
roller stacks are clamped between the bearing hub top and bottom, and
fixed by a screw and nut."""


