[inputs]
pump_housing_front_with_stepper = {quantity=1}
bearing_roller = {quantity=1}
pump_housing_rear_with_stepper = {quantity=1}
tube_support = {quantity=1}

[inputs.silicone_tubing]
type = "silicone tubing, 6mm OD, 4mm ID"
quantity = "1 meter"
comment = "PVC tube isn't flexible enough.  Adjust quantity to suit your application."

[inputs.m4_25_bhcs]
name = "m4_25_bhcs"
type = "M4x25 BHCS"
quantity = 4
comment = """BHCS is preferred over SHCS so the screw heads sit recessed
below the surface of the pump body."""

[inputs.m4_nuts]
type = "M4 nuts"
quantity = 4

[[dependencies]]
tools = [ "3 mm hex driver" ]
operator = {skill="assembly"}

[[action]]
process = """Press the bearing roller assembly onto the motor shaft of the
rear pump housing assembly.  Install the tubing so it goes in one port,
around the roller, and out the other port.  Press the motor shaft of the
front pump housing assembly into the other side of the bearing roller.
Attach with the screws and nuts."""

