[outputs]
pump_housing_rear = {}

[inputs]
pump_housing_rear_untapped = {}

[dependencies]
tools = [ "M4 tap" ]
operator = { skills=["tapping"] }

[action]
process = """Tap the two motor mounting holes."""
