[outputs]
pump_housing_rear = {quantity=1}

[inputs]
pump_housing_rear_untapped = {quantity=1}

[dependencies]
tools = [ "M4 tap" ]
operator = { skills=["tapping"] }

[action]
process = """Tap the two motor mounting holes."""
