[outputs]
pump_housing_front_with_stepper={}

[inputs]
pump_housing_front={version=0.1}
m4_5_shcs={quantity={amount=2}, description="M4x5 SHCS"}
stepper_28byj_48={}

[dependencies]
tools = [ "3 mm hex driver" ]
operator = {skills=["assembly"]}

[action]
process = """Screw the stepper to the printed front housing."""