[outputs]
pump_housing_front={}

[inputs]
pump_housing_front_untapped={version=0.1, type="printed"}

[dependencies]
tools = [ "M4 tap" ]
operator = {skills=["tapping"]}

[action]
process = """Tap the two motor mounting holes."""

