[inputs]
capital = { quantity = { amount=2.59, unit="USDollar" } }

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://acmehydroponics.net/collections/plumbing/products/fill-drain-1-2-fitting",
    "https://www.ebay.com/itm/134772441988",
    "https://www.ebay.com/itm/251050375775?var=554293415440",
    "https://www.ebay.com/itm/251313018420",
]
