[outputs.clay_pebble_grow_medium]
quantity = { amount=10, unit="Liter" }
comments = "Any clay pebbles will do, 10L is plenty."
image = "clay_pebbles.webp"

[inputs]
capital = { quantity = { amount=15.19, unit="USDollar" } }

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://hydrobuilder.com/products/grow-t-clay-pebbles-4mm-16mm-10-liters"
]
