[outputs.controller]
comments = """Lots of room for variation here.  This reference design is a Pi with a simple timer app to turn the lights and pump on and off on a fixed schedule."""

[inputs]
raspberry_pi = {}
micro_sd_card = {}
pi_power_supply = {}
pi_enclosure = {}

[dependencies]
operator = {skills=["vendor interaction"]}

[action]
process = """
* Flash the MicroSD card with a modern Raspberry Pi OS.
* Connect all the pieces together.
* Install Rust.
* Build the repo at <https://github.com/Taproot-Manufacturing-Syndicate/hydroponics-controller>.
* Make a JSON config file.
* Add a systemd service to run the hydroponics-controller.
"""
