[inputs]
capital = { quantity = { amount=0.96, unit="USDollar" } }

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://acmehydroponics.net/collections/plumbing/products/screen-fitting-plumbing",
    "https://hydrobuilder.com/products/grow1-ebb-flow-screen-fittings-pack-of-10",
    "https://www.ebay.com/itm/256644061627"
]
