[outputs]
hose_1_inch = { quantity = { amount=100, unit="Foot" } }

[inputs]
capital = { quantity = { amount=15.19, unit="USDollar" } }

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://www.botanicare.com/products/fittings/"
]
