[inputs]
food_safe_bucket_lid = {}
#plant_tray_basin = {}

[dependencies]
tools = [ "hacksaw", "sharpie" ]

[action]
process = """
Make the `plant_tray_basin` first. (FIXME: There's currently no way to
enforce ordering of the steps in the job compiler.)

- Use the two holes drilled in the `plant_tray_basin` to mark the
`food_safe_bucket_lid` with the locations of the two fittings.

- Add a space for the nuts that attach the fittings from the bottom of
the plant_tray_basin`.

- Cut the lid to make room for the two barb fittings, so the
`plant_tray_basin` can sit in the lid comfortably.  This cut will also
make room for the `nutrient_pump` power cord to exit."""
