[outputs.nutrient_pump]
comments = """Active Aqua 160 GPH.

The smaller 40 GPH version is not appropriate.

I like that they publish GPH vs lift height curves, and it falls off
pretty rapidly for the smaller pumps.

The 160 GPH and 250 GPH both use 1/2 inch tubing, so i'll try one of
those, easy to switch to the other one if the first one's no good."""

image = "active-aqua-160-gph.png"

[inputs]
capital={quantity={amount=21.69, unit="USDollar"}}

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://hydrobuilder.com/products/active-aqua-submersible-water-pump-160-gph",
    "https://hydrobuilder.com/active-aqua-submersible-water-pumps.html",
    "https://www.ebay.com/itm/261229407962",
    "https://www.ebay.com/itm/373981715463",
]
