[outputs]
plant_tray_basin = { comment = "Alternatively use commercial plastic bus tubs." }

[inputs]
food_safe_5_gallon_bucket = {}

[dependencies]
tools = [ "hacksaw", "35mm hole saw (this is the correct size for both barb fittings)" ]

[action]
process = """
* Find good locations for the two barb fittings (for the pump and the
drain). The fittings should be near the edge of the `plant_tray_basin`
and pretty close together, but far enough apart that there's room for the
nuts on the underside that compress the barb fitting gaskets against the
`plant_tray_basin` floor.

* Mark the locations of the holes.

* Drill holes for the two fittings.

* Temporarily install the overflow fitting, and mark the wall of the
bucket a few inches above the top of the overflow fitting.

* Cut the top of the bucket off at the mark.  This leaves a kind of deep
dish or bowl that will holds the plant growth medium and the plants.

"""
