[inputs]
plant_tray_basin = {}
clay_pebble_grow_medium = { quantity = { amount=5, unit="Liter" } }
pump_fitting = {}
overflow_fitting = {}

[dependencies]

[action]
process = """
* Attach the pump fitting.
* Attach the overflow fitting.
* Add the grow medium.
"""
