[inputs]
food_safe_5_gallon_bucket = {}
clay_pebble_grow_medium = { quantity = { amount=5, unit="Liter" } }
barb_fitting_1_inch = {}
barb_fitting_1_2_inch = {}

[dependencies]
tools = [ "hack saw" ]

[action]
process = """Cut the top of the bucket off, leaving a kind of deep dish
or bowl that will holds the plant growth medium and the plants.

Drill holes for the two fittings.

Attach the two fittings.

Add the grow medium """
