[outputs]
plant_tray_basin = { comment = "Alternatively use commercial plastic bus tubs." }

[inputs]
food_safe_5_gallon_bucket = {}

[dependencies]
tools = [ "hack saw", "step drill correct size for both barb fittings" ]

[action]
process = """

* Drill holes for the two fittings.  The holes should be pretty close
together, but far enough apart that there's sufficient room for the nuts
that compress the barb fitting gaskets.

* Temporarily install the overflow fitting, and mark the wall of the
bucket a few inches above the top of the overflow fitting.

* Cut the top of the bucket off at the mark.  This leaves a kind of deep
dish or bowl that will holds the plant growth medium and the plants.
a few inches above the top of the overflow fitting.

"""
