[outputs]
filament = { quantity = { amount = 1000, unit = "Gram" } }

[inputs]
capital={ quantity = { amount=23.99, unit="USDollar" } }

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://www.hatchbox3d.com/collections/abs-1-75mm/products/3d-abs-1kg1-75-red"
]