[outputs]
m4_25_bhcs = {quantity={amount=100}}

[inputs]
capital={quantity={amount=18.45, unit="USDollar"}}

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://www.ebay.com/itm/116208880863?var=416418791413"
]