[outputs]
m4_20_shcs = {quantity={amount=100}}

[inputs]
capital={quantity={amount=13.65, unit="USDollar"}}

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://www.ebay.com/itm/116208880820?var=416418584787"
]