[outputs.bearing_624]
quantity = { amount=10 }
comments = "13mm OD, 4mm ID, 5mm wide"

[inputs]
capital={quantity={amount=8.99, unit="USDollar"}}

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://www.ebay.com/itm/162442914585"
]