[outputs]
m4_20_shcs = {quantity=100}

[inputs]
capital={amount="13.65 usd"}

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://www.ebay.com/itm/116208880820?var=416418584787"
]