[outputs]
m4_nuts = {quantity={amount=100}}

[inputs]
capital = { quantity = { amount = 1.35, unit = "USDollar" } }

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://www.ebay.com/itm/116208880811?var=416418360544"
]