[outputs.m4_washer]
quantity = { amount=100 }
comments = "4.4 mm ID, 8.8 mm OD, 0.8 mm thick"

[inputs]
capital={quantity={amount=7.18, unit="USDollar"}}

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://www.ebay.com/itm/116208880905?var=416418468720"
]