[outputs]
silicone_tubing = {quantity={amount=3, unit="Meter"}}

[inputs]
capital={quantity={amount=18.75, unit="USDollar"}}

[dependencies]
operator = {skills=["vendor interaction"]}

[action.purchase]
vendor = [
    "https://www.ebay.com/itm/134871649335"
]