[outputs]
bearing_hub={version=0.1, type="printed"}

[inputs]
filament={}

[dependencies]
tools=["fdm-printer"]

[config]
model="https://github.com/DerSchultze/Peristaltic-Controller@92a4d9b:stl/bearing-hub.STL"

[action]
print={}