[outputs]
bearing_hub={version=0.1, type="printed"}

[inputs]
filament={}

[dependencies]
tools=["fdm-printer"]

[action]
print = { model="https://github.com/DerSchultze/Peristaltic-Controller/blob/92a4d9b/stl/bearing-hub.STL", profile="placeholder" }